import type { AppNotification } from '@/domain';

import { conversationId, leadId, notificationId, visitId } from './ids';
import type { SeedPicks } from './picks';
import type { SeedTime } from './time';

/** 14 notifications. Every `deepLink` is validated against real routes and existing entities in tests. */
export function buildNotifications(t: SeedTime, picks: SeedPicks): AppNotification[] {
  return [
    {
      id: notificationId(1),
      type: 'ACTION_REQUIRED',
      title: 'Follow-up due · Rahul Sharma',
      body: `Follow up on the Real Rise shortlist at ${t.timeLabel('10:30')}.`,
      createdAt: t.at(0, '08:30'),
      read: false,
      deepLink: `/leads/${leadId(1)}`,
    },
    {
      id: notificationId(2),
      type: 'ACTION_REQUIRED',
      title: 'New lead · Ananya Iyer',
      body: 'Website enquiry. Send an introduction and project options.',
      createdAt: t.at(0, '08:10'),
      read: false,
      deepLink: `/leads/${leadId(2)}`,
    },
    {
      id: notificationId(3),
      type: 'FOLLOW_UP',
      title: 'Overdue · Mohammed Faizan',
      body: `Call back on the payment plan was due ${t.dayLabel(-1)}, ${t.timeLabel('18:00')}.`,
      createdAt: t.at(-1, '18:00'),
      read: false,
      deepLink: `/leads/${leadId(3)}`,
    },
    {
      id: notificationId(4),
      type: 'UPDATE',
      title: 'New message · Imran Qureshi',
      body: 'Please call me after 5 PM.',
      createdAt: t.at(0, '07:45'),
      read: false,
      deepLink: `/conversations/${conversationId(3)}`,
    },
    {
      id: notificationId(5),
      type: 'INVENTORY',
      title: `Hold ending · Plot ${picks.arjunHeldPlot.plotNumber} · Cedar Enclave`,
      body: `The prototype hold ends ${t.dayLabel(1)}, ${t.timeLabel('20:00')}.`,
      createdAt: t.at(0, '09:00'),
      read: false,
      deepLink: `/plots/${picks.arjunHeldPlot.id}`,
    },
    {
      id: notificationId(6),
      type: 'FOLLOW_UP',
      title: 'Site visit today · Rohit Bansal',
      body: `Cedar Enclave at ${t.timeLabel('12:00')}. Confirm with the customer.`,
      createdAt: t.at(0, '08:00'),
      read: false,
      deepLink: `/visits/${visitId(2)}`,
    },
    {
      id: notificationId(7),
      type: 'FOLLOW_UP',
      title: 'Site visit today · Rahul Sharma',
      body: `Real Rise at ${t.timeLabel('15:30')}.`,
      createdAt: t.at(0, '08:00'),
      read: false,
      deepLink: `/visits/${visitId(1)}`,
    },
    {
      id: notificationId(8),
      type: 'INVENTORY',
      title: `Plot ${picks.otherBookedPlot.plotNumber} booked · Real Rise`,
      body: 'This plot is no longer available to shortlist.',
      createdAt: t.at(-1, '14:20'),
      read: true,
      deepLink: `/plots/${picks.otherBookedPlot.id}`,
    },
    {
      id: notificationId(9),
      type: 'UPDATE',
      title: 'Visit feedback recorded · Mohammed Faizan',
      body: 'Outcome: very interested. Two plots shortlisted.',
      createdAt: t.at(-3, '15:45'),
      read: true,
      deepLink: `/visits/${visitId(4)}`,
    },
    {
      id: notificationId(10),
      type: 'ACTION_REQUIRED',
      title: 'Booking documents pending · Arjun Patel',
      body: 'KYC checklist is due before the hold ends.',
      createdAt: t.at(-1, '20:05'),
      read: false,
      deepLink: `/leads/${leadId(7)}`,
    },
    {
      id: notificationId(11),
      type: 'INVENTORY',
      title: `Hold ending today · Plot ${picks.expiringHoldPlot.plotNumber} · Aurelia Greens`,
      body: `The prototype hold ends at ${t.timeLabel('18:00')}. Release it or convert it.`,
      createdAt: t.at(0, '08:45'),
      read: false,
      deepLink: `/plots/${picks.expiringHoldPlot.id}`,
    },
    {
      id: notificationId(12),
      type: 'UPDATE',
      title: 'Prototype mode',
      body: 'You’re viewing seeded prototype data. Nothing here is live.',
      createdAt: t.at(0, '07:00'),
      read: true,
      deepLink: '/settings',
    },
    {
      id: notificationId(13),
      type: 'FOLLOW_UP',
      title: 'Follow-up scheduled · Pooja Deshmukh',
      body: `Follow up on shortlist feedback on ${t.dayLabel(2)}.`,
      createdAt: t.at(-1, '12:00'),
      read: true,
      deepLink: `/leads/${leadId(17)}`,
    },
    {
      id: notificationId(14),
      type: 'UPDATE',
      title: 'Lead won · Kavitha Menon',
      body: `Booking confirmed for Plot ${picks.kavithaBookedPlot.plotNumber} at Real Rise.`,
      createdAt: t.at(-6, '16:00'),
      read: true,
      deepLink: `/leads/${leadId(8)}`,
    },
  ];
}
