import type { Facing, Plot, PlotStatus } from '@/domain';

import { plotId } from './ids';
import { PROJECT_BLUEPRINTS, type ProjectBlueprint } from './projects';
import type { SeedTime } from './time';

/**
 * 120 plots across 4 projects, generated by pure formulas (no Math.random) so the inventory is
 * identical on every launch. Statuses use a step-5 walk over a 12-cycle, which scatters them across
 * the grid while guaranteeing every status appears in every project. Sizes, facings and road widths
 * use an integer hash so no cycle length can alias into a constant.
 */
const STATUS_CYCLE: readonly PlotStatus[] = [
  'AVAILABLE',
  'AVAILABLE',
  'BOOKED',
  'AVAILABLE',
  'ON_HOLD',
  'AVAILABLE',
  'AVAILABLE',
  'BOOKED',
  'AVAILABLE',
  'BLOCKED',
  'AVAILABLE',
  'NOT_FOR_SALE',
];
const FACINGS: readonly Facing[] = [
  'EAST',
  'NORTH',
  'EAST',
  'WEST',
  'SOUTH',
  'NORTH',
  'EAST',
  'WEST',
];
const ROAD_WIDTHS_FT: readonly number[] = [30, 40, 40, 60];

const CORNER_PREMIUM = 0.05;
const VASTU_FACING_PREMIUM = 0.02; // north / east
const PREMIUM_ROUNDING = 1_000;

/** Deterministic 32-bit integer hash (no aliasing against small modulo lengths). */
function scatter(n: number, salt: number): number {
  let h = Math.imul(n, 374_761_393) + Math.imul(salt, 668_265_263);
  h = Math.imul(h ^ (h >>> 13), 1_274_126_177);
  return (h ^ (h >>> 16)) >>> 0;
}

function pick<T>(items: readonly T[], index: number): T {
  const value = items[index % items.length];
  if (value === undefined) throw new Error('pick() called with an empty list');
  return value;
}

const roundTo = (value: number, step: number) => Math.round(value / step) * step;

/**
 * Plots the demo narrative depends on. Each is pinned so a lead's shortlist / booking always fits
 * that lead's budget, size and facing (asserted in the seed tests). `holdAt` fixes when a hold
 * ends, instead of depending on generation order.
 */
export const DEMO_PLOT_IDS = {
  /** Rahul Sharma's walkthrough plot: Real Rise · Plot 26 · 240 sq yd · Available. */
  rahul: plotId('rr', 26),
  /** Kavitha Menon's booked plot (WON). */
  kavithaBooked: plotId('rr', 8),
  /** Pooja Deshmukh's shortlist. */
  pooja: plotId('rr', 14),
  /** Mohammed Faizan's corner plot (available) and held plot. */
  faizanCorner: plotId('ag', 12),
  faizanHeld: plotId('ag', 7),
  /** Aurelia Greens hold that ends today (drives an inventory notification). */
  expiringHold: plotId('ag', 19),
  /** Arjun Patel's plot on Prototype Hold. */
  arjunHeld: plotId('ce', 10),
} as const;

type PlotOverride = Partial<Omit<Plot, 'holdExpiresAt'>> & {
  holdAt?: readonly [dayOffset: number, hhmm: string];
};

const PLOT_OVERRIDES: Record<string, PlotOverride> = {
  [DEMO_PLOT_IDS.rahul]: {
    status: 'AVAILABLE',
    areaSqYd: 240,
    facing: 'EAST',
    roadWidthFt: 40,
    isCorner: false,
  },
  [DEMO_PLOT_IDS.kavithaBooked]: {
    status: 'BOOKED',
    areaSqYd: 240,
    facing: 'EAST',
    roadWidthFt: 40,
    isCorner: false,
  },
  [DEMO_PLOT_IDS.pooja]: {
    status: 'AVAILABLE',
    areaSqYd: 240,
    facing: 'NORTH',
    roadWidthFt: 40,
    isCorner: false,
  },
  [DEMO_PLOT_IDS.faizanCorner]: {
    status: 'AVAILABLE',
    areaSqYd: 333,
    facing: 'EAST',
    roadWidthFt: 60,
    isCorner: true,
  },
  [DEMO_PLOT_IDS.faizanHeld]: {
    status: 'ON_HOLD',
    areaSqYd: 400,
    facing: 'NORTH',
    roadWidthFt: 40,
    isCorner: false,
    holdAt: [2, '12:00'],
  },
  [DEMO_PLOT_IDS.expiringHold]: { status: 'ON_HOLD', holdAt: [0, '18:00'] },
  [DEMO_PLOT_IDS.arjunHeld]: {
    status: 'ON_HOLD',
    areaSqYd: 300,
    facing: 'NORTH',
    roadWidthFt: 60,
    isCorner: true,
    holdAt: [1, '20:00'],
  },
};

/** Default hold expiries for un-pinned holds: tomorrow 8 PM, today 6 PM, in two days. */
const DEFAULT_HOLD_TIMES: readonly (readonly [number, string])[] = [
  [1, '20:00'],
  [0, '18:00'],
  [2, '12:00'],
];

function buildPlot(bp: ProjectBlueprint, n: number, holdOrdinal: number, t: SeedTime): Plot {
  const id = plotId(bp.key, n);
  const override = PLOT_OVERRIDES[id] ?? {};
  const salt = bp.variation;

  const status = override.status ?? pick(STATUS_CYCLE, n * 5 + salt);
  const areaSqYd = override.areaSqYd ?? pick(bp.areaOptionsSqYd, scatter(n, salt * 3 + 1));
  const facing = override.facing ?? pick(FACINGS, scatter(n, salt * 3 + 2));
  const roadWidthFt = override.roadWidthFt ?? pick(ROAD_WIDTHS_FT, scatter(n, salt * 3 + 3));
  const isCorner = override.isCorner ?? n % 6 === 0;

  const block = n <= bp.blockACount ? 'A' : 'B';
  const baseRatePerSqYd = bp.ratePerSqYd[block];
  const baseCost = areaSqYd * baseRatePerSqYd;

  const premiumRate =
    (isCorner ? CORNER_PREMIUM : 0) +
    (facing === 'EAST' || facing === 'NORTH' ? VASTU_FACING_PREMIUM : 0);
  const premium = roundTo(baseCost * premiumRate, PREMIUM_ROUNDING);

  const holdAt = override.holdAt ?? pick(DEFAULT_HOLD_TIMES, holdOrdinal);

  return {
    id,
    projectId: bp.id,
    plotNumber: String(n),
    phase: n <= bp.phaseOneCount ? 'Phase 1' : 'Phase 2',
    block: `Block ${block}`,
    status,
    areaSqYd,
    facing,
    roadWidthFt,
    isCorner,
    baseRatePerSqYd,
    ...(premium > 0 ? { premiumAmount: premium } : {}),
    estimatedTotal: baseCost + premium,
    ...(status === 'ON_HOLD' ? { holdExpiresAt: t.at(holdAt[0], holdAt[1]) } : {}),
  };
}

export function buildPlots(t: SeedTime): Plot[] {
  return PROJECT_BLUEPRINTS.flatMap((bp) => {
    let holdOrdinal = 0;
    return Array.from({ length: bp.plotCount }, (_, i) => {
      const plot = buildPlot(bp, i + 1, holdOrdinal, t);
      if (plot.status === 'ON_HOLD') holdOrdinal += 1;
      return plot;
    });
  });
}
