import type { Permission, Role } from '@/domain';

const ALL_PERMISSIONS: Permission[] = [
  'EMPLOYEE_VIEW_ALL',
  'EMPLOYEE_VIEW_DOWNLINE',
  'EMPLOYEE_CREATE',
  'EMPLOYEE_EDIT',
  'EMPLOYEE_CHANGE_STATUS',
  'EMPLOYEE_ASSIGN_ROLE',
  'EMPLOYEE_ASSIGN_MANAGER',
  'TEAM_MANAGE',
  'PROJECT_MANAGE',
  'PROJECT_SITE_MANAGE',
  'PLOT_MANAGE_INVENTORY',
  'PLOT_MANAGE_PRICING',
  'VEHICLE_MANAGE',
  'COMMISSION_RULE_MANAGE',
  'COMMISSION_RULE_VIEW',
  'LEAD_VIEW_ALL',
  'LEAD_VIEW_TEAM',
  'LEAD_VIEW_OWN',
  'LEAD_ASSIGN',
  'LEAD_EDIT',
  'CUSTOMER_VIEW_ALL',
  'CUSTOMER_VIEW_TEAM',
  'CUSTOMER_VIEW_OWN',
  'CUSTOMER_MANAGE',
  'FOLLOW_UP_MANAGE',
  'TASK_MANAGE',
  'CONVERSATION_VIEW',
  'CONVERSATION_SEND',
  'NOTIFICATION_VIEW',
  'SITE_VISIT_TICKET_CREATE',
  'SITE_VISIT_TICKET_VIEW_OWN',
  'SITE_VISIT_TICKET_VIEW_TEAM',
  'SITE_VISIT_TICKET_VIEW_ALL',
  'SITE_VISIT_TICKET_REVIEW_MARKETING',
  'SITE_VISIT_TICKET_REVIEW_MANAGEMENT',
  'SITE_VISIT_TICKET_ASSIGN_VEHICLE',
  'SITE_VISIT_TICKET_MODIFY',
  'SITE_VISIT_TICKET_CANCEL',
  'DASHBOARD_VIEW_ORG',
  'DASHBOARD_VIEW_TEAM',
  'DASHBOARD_VIEW_OWN',
];

export const ROLE_ID = {
  ceo: 'role_ceo',
  management: 'role_management',
  marketingHead: 'role_marketing_head',
  seniorAssociate: 'role_senior_associate',
  juniorAssociate: 'role_junior_associate',
} as const;

/**
 * The five system roles (`isSystem: true`). Management may add more roles at the same `orgLevel`
 * later (spec §3) — this seed only guarantees one role per level exists out of the box.
 */
export function buildRoles(): Role[] {
  return [
    {
      id: ROLE_ID.ceo,
      key: 'ceo',
      label: 'CEO / Owner',
      orgLevel: 'CEO',
      permissions: ALL_PERMISSIONS,
      isSystem: true,
    },
    {
      id: ROLE_ID.management,
      key: 'management',
      label: 'Management',
      orgLevel: 'MANAGEMENT',
      permissions: ALL_PERMISSIONS,
      isSystem: true,
    },
    {
      id: ROLE_ID.marketingHead,
      key: 'marketing_head',
      label: 'Marketing Head',
      orgLevel: 'MARKETING_HEAD',
      permissions: [
        'EMPLOYEE_VIEW_DOWNLINE',
        'TEAM_MANAGE',
        'COMMISSION_RULE_VIEW',
        'LEAD_VIEW_TEAM',
        'LEAD_ASSIGN',
        'CUSTOMER_VIEW_TEAM',
        'FOLLOW_UP_MANAGE',
        'TASK_MANAGE',
        'CONVERSATION_VIEW',
        'CONVERSATION_SEND',
        'NOTIFICATION_VIEW',
        'SITE_VISIT_TICKET_VIEW_TEAM',
        'SITE_VISIT_TICKET_REVIEW_MARKETING',
        'DASHBOARD_VIEW_TEAM',
      ],
      isSystem: true,
    },
    {
      id: ROLE_ID.seniorAssociate,
      key: 'senior_associate',
      label: 'Senior Associate',
      orgLevel: 'SENIOR_ASSOCIATE',
      permissions: [
        'EMPLOYEE_VIEW_DOWNLINE',
        'EMPLOYEE_CREATE',
        'LEAD_VIEW_OWN',
        'LEAD_EDIT',
        'CUSTOMER_VIEW_OWN',
        'CUSTOMER_MANAGE',
        'FOLLOW_UP_MANAGE',
        'TASK_MANAGE',
        'CONVERSATION_VIEW',
        'CONVERSATION_SEND',
        'NOTIFICATION_VIEW',
        'SITE_VISIT_TICKET_CREATE',
        'SITE_VISIT_TICKET_VIEW_OWN',
        'SITE_VISIT_TICKET_MODIFY',
        'SITE_VISIT_TICKET_CANCEL',
        'DASHBOARD_VIEW_OWN',
      ],
      isSystem: true,
    },
    {
      id: ROLE_ID.juniorAssociate,
      key: 'junior_associate',
      label: 'Junior Associate',
      orgLevel: 'JUNIOR_ASSOCIATE',
      permissions: [
        'LEAD_VIEW_OWN',
        'CUSTOMER_VIEW_OWN',
        'TASK_MANAGE',
        'CONVERSATION_VIEW',
        'NOTIFICATION_VIEW',
        'SITE_VISIT_TICKET_VIEW_OWN',
        'DASHBOARD_VIEW_OWN',
      ],
      isSystem: true,
    },
  ];
}
